spring:
  config:
    import: classpath:/application-prod.yml,classpath:/datasource-prod.yml
  mail:
    host: smtp.qq.com
    port: 465
    username:
    password:
    properties:
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
goalias:
  jwt:
    userSecretKey: goalias
    userTtl: 180000
    userTokenName: token
  alioss:
    endpoint:
    accessKeyId:
    accessKeySecret:
    bucketName:
  aliyun:
    accessKeyId:
    accessKeySecret:
    endpoint:
  minio:
    endpoint: http://minio-goalias:9000
    accessKey:
    secretKey:
  canal:
    hostname: canal-goalias
    port: 11111
    destination: example
    update: true
    insert: true
    delete: true
    schema: goalias
    user-table: user
  log:
    isOpen: true


