spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username:
    password: 
    url: 
    type: com.alibaba.druid.pool.DruidDataSource
    #http://127.0.0.1:9999/druid/sql.html

  redis:
    host: 
    port: 
    password: 
    database: 

